### PR TITLE
record objective evolution over time

### PR DESCRIPTION
**Pull request by augustindelecluse**
If we want to compute values based on the objective evolution, we need to record the evolution over time of the objective and print it at the end of the program.

This adds a class called after every move, that checks if the objective has been improved, and store the timestamp for the improvements as well as the objective value.

An example of output for objective timestamps can be

```
obj=[(t=0.077-v=104001030000)-(t=0.132-v=102002075009)-(t=0.174-v=100003122851)-(t=0.246-v=98003164604)-(t=0.286-v=96004190604)-(t=0.316-v=94004229594)-(t=0.345-v=92004284433)-(t=0.369-v=90005317803)-(t=0.395-v=88006352054)-(t=0.429-v=86007387154)-(t=0.486-v=84007453964)-(t=0.519-v=82008488329)-(t=0.527-v=82008446708)-(t=0.554-v=80008460641)-(t=0.562-v=78009500609)-(t=0.616-v=76010536327)-(t=0.652-v=74010556602)-(t=0.685-v=72011595840)-(t=0.705-v=70011623926)-(t=0.727-v=68012672305)-(t=0.745-v=66012718237)-(t=0.752-v=64012731074)-(t=0.776-v=62012799077)-(t=0.803-v=60012833728)-(t=0.826-v=58012919294)-(t=0.851-v=56012971704)-(t=0.875-v=54014016666)-(t=0.898-v=52014050153)-(t=0.916-v=50015093235)-(t=0.940-v=48015151709)-(t=0.961-v=46015186588)-(t=0.978-v=44016234273)-(t=0.993-v=42016306955)-(t=0.995-v=42016305175)-(t=1.011-v=40017352356)-(t=1.031-v=38017356789)]
```

It is a list of tuples composed of time (in seconds) and objective value. The list is intentionally not using commas, so that it can be safely put into a column of a CSV file, but I'm not opposed to putting commas instead to be more clear.

Check & Run with 

```
solveInstance --input examples/pdptw_100/lc101.txt --timeout 1 --bandit epsilongreedynew --verbosity 1
```

The last line printed is the objective improvement over time

### CODE REVIEW

**Comment by smi-cetic** [comment]
Hi @FabianGermeau , regarding the ability to record the best known solutions with timestamps: the solution implemented here by @augustindelecluse works, but I was wondering if one can do it with native OscaR utilities - maybe the profiler? 

I was hoping it could be the same mechanism that is used when getting verbosity 1 console output, but then I saw that that job is done entirely in the `doAllMoves` function...

**Comment by FabianGermeau** [comment]
Using the Profiler could have been a good idea but, here you consider only solution where everything is routed. It's not possible to make the difference in the Profiler. It only gets the new value of the obj.

The way Augustin did it is the simplest way of doing it. Otherwise you'ld have to rewrite a lot a stuff.

Or by implementing a new Combinator ? (and put all the code in it)

**Comment by FabianGermeau** [comment]
Other than that seems good to me :)

**Review by FabianGermeau — APPROVED** [review]

**Comment by smi-cetic** [comment]
> Other than that seems good to me :)

Thanks a lot!

**Pull request merged**
